apiVersion: apps/v1
kind: Deployment
metadata:
  name: productstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productstore
  template:
    metadata:
      labels:
        app: productstore
    spec:
      containers:
      - name: productstore
        image: ghcr.io/sonalidesarda/productstore:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "host.docker.internal:9092"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: productstore-service
spec:
  selector:
    app: productstore
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - name: solr
        image: solr:9
        ports:
        - containerPort: 8983
        args:
          - solr-precreate
          - products
---
apiVersion: v1
kind: Service
metadata:
  name: solr-service
spec:
  selector:
    app: solr
  ports:
    - protocol: TCP
      port: 8983
      targetPort: 8983
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-search-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-search-worker
  template:
    metadata:
      labels:
        app: product-search-worker
    spec:
      containers:
      - name: product-search-worker
        image: ghcr.io/sonalidesarda/product-search-worker:latest
        imagePullPolicy: Always
        env:
        - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
          value: "host.docker.internal:9092"
        - name: SOLR_URL
          value: "http://solr-service:8983/solr"